# Generated by Django 4.1.6 on 2023-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_ruc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='usuario_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='per_cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='per_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='per_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='usuario_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prioridades',
            name='usuario_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='usuario_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminales',
            name='usuario_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='usuario_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='tc_desc',
            field=models.CharField(max_length=70),
        ),
    ]
