# Generated by Django 4.1.7 on 2023-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clientes_cli_razon_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='colas',
            name='cola_entrada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='colas',
            name='cola_salida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prioridades',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prioridades',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='terminales',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='terminales',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
